### ISSUE TITLE
Getting `SyntaxError: Unexpected token .` when doing `node dist/index.js -c config.json`

### ISSUE THREAD

**Issue by commjoen** [DJLemkes/mia#1]
While trying to follow the readme steps, at step  `node dist/index.js -c config.json` I get the following stacktrace:

```sh
/workspace/mia/dist/src/run/aws.js:27
    const regions = config.aws?.regions || [];
                               ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/razor/Documents/workspace/yolt/code/mia/dist/index.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
```

How can I proceed?

I am using MacOS-X and node v12.0.0 (npm v7.19.1).

**Comment by commjoen** [comment]
Issue can be closed when using node v16.
